---
# Source: dask/templates/dask-scheduler-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: coffea-dask-scheduler
  labels:
    app: dask
    heritage: "Helm"
    release: "coffea-dask"
    chart: dask-4.1.1
    component: scheduler
spec:
  ports:
    - name: coffea-dask-scheduler
      port: 8786
      targetPort: 8786
    - name: coffea-dask-webui
      port: 8787
      targetPort: 8787
  selector:
    app: dask
    release: "coffea-dask"
    component: scheduler
  type: LoadBalancer
---
# Source: dask/templates/dask-scheduler-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffea-dask-scheduler
  labels:
    app: dask
    heritage: "Helm"
    release: "coffea-dask"
    chart: dask-4.1.1
    component: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dask
      release: "coffea-dask"
      component: scheduler
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dask
        release: "coffea-dask"
        component: scheduler
    spec:
      imagePullSecrets:
        null
      containers:
        - name: coffea-dask-scheduler
          image: "coffeateam/coffea-dask:0.1.16"
          imagePullPolicy: IfNotPresent
          args:
            - dask-scheduler
            - --port
            - "8786"
            - --bokeh-port
            - "8787"
          ports:
            - containerPort: 8786
            - containerPort: 8787
          resources:
            requests:
              cpu: 2
              memory: 4G
            limits:
              cpu: 2
              memory: 4G
          env:
            null
          volumeMounts:
          - mountPath: /opt/app
            name: scratch-volume
      volumes:
      - name: scratch-volume
        emptyDir: {}
---
# Source: dask/templates/dask-worker-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffea-dask-worker
  labels:
    app: dask
    heritage: "Helm"
    release: "coffea-dask"
    chart: dask-4.1.1
    component: worker
spec:
  replicas: 15
  selector:
    matchLabels:
      app: dask
      release: "coffea-dask"
      component: worker
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dask
        release: "coffea-dask"
        component: worker
    spec:
      imagePullSecrets:
        null
      containers:
        - name: coffea-dask-worker
          image: "coffeateam/coffea-dask:0.1.16"
          imagePullPolicy: IfNotPresent
          args:
            - dask-worker
            - coffea-dask-scheduler:8786
            - --no-dashboard
            - --nthreads
            - "4"
          ports:
            - containerPort: 8789
          resources:
            requests:
              cpu: 3.9
              memory: 7G
            limits:
              cpu: 4
              memory: 8G
          env:
          - name: MALLOC_MMAP_THRESHOLD_
            value: "16384"
          volumeMounts:
          - mountPath: /opt/app
            name: scratch-volume
          - mountPath: /opt/columnstore
            name: columnstore
      volumes:
      - name: scratch-volume
        emptyDir: {}
      - name: columnstore
        persistentVolumeClaim:
          claimName: columnstore
---
# Source: dask/templates/dask-scheduler-ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: coffea-dask-scheduler
  labels:
    app: coffea-dask-scheduler
    chart: "dask-4.1.1"
    release: "coffea-dask"
    heritage: "Helm"
  annotations:
    null
spec:
  rules:
  - host: coffea-dask.fnal.gov
    http:
      paths:
      - backend:
          serviceName: coffea-dask-scheduler
          servicePort: 8787
