nameOverride: ""
fullnameOverride: ""

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: coffea-farm.example.edu
  tls: []

columnservice:
  replicas: 2

  image:
    repository: coffeateam/coffea-columnservice
    tag: 0.1.0
    pullPolicy: IfNotPresent
  imagePullSecrets: []

  podSecurityContext: {}
    # fsGroup: 2000
  securityContext:
    runAsUser: 1000340000

  bucketname: columnservice
  env: {}

  resources:
    limits:
      cpu: 1
      memory: 512Mi

  nodeSelector: {}
  tolerations: []
  affinity: {}

  service:
    type: ClusterIP
    port: 8000

minio:
  securityContext:
    enabled: true
    fsGroup: 1000340000
    runAsUser: 1000340000
  mode: distributed
  statefulset:
    replicaCount: 4
  accessKey:
    forcePassword: true
  secretKey:
    forcePassword: true
  resources:
    limits:
      cpu: 500m
      memory: 2Gi
  global:
    storageClass: glusterfs-registry-block
  persistence:
    size: 45Gi
  podAnnotations:
     prometheus.io/scrape: "true"
     prometheus.io/path: "/minio/prometheus/metrics"
     prometheus.io/port: "9000"

mongodb:
  securityContext:
    enabled: true
    fsGroup: 1000340000
    runAsUser: 1000340000
  mongodbDatabase: coffeadb
  mongodbUsername: coffea
  mongodbRootPassword: ""
  mongodbPassword: ""
  resources:
    limits:
      cpu: 1
      memory: 2G
  metrics.enabled: true

scheduler:
  image:
    repository: coffeateam/coffea-columnservice
    tag: 0.1.0
    pullPolicy: IfNotPresent
  replicas: 1
  env: {}
  service:
    type: LoadBalancer
    port: 8786
    uiport: 8787
    externalIPs: []
  resources:
    limits:
      cpu: 1
      memory: 2G
  tolerations: []
  nodeSelector: {}
  affinity: {}

worker:
  image:
    repository: coffeateam/coffea-columnservice
    tag: 0.1.0
    pullPolicy: IfNotPresent
  scratchDir:
    mountPath: /opt/app
  replicas: 20
  env:
  - name: MALLOC_MMAP_THRESHOLD_
    value: "16384"
  resources:
    limits:
      cpu: 2
      memory: 4G
  tolerations: []
  nodeSelector: {}
  affinity: {}

notebook:
  enabled: false
  image:
    repository: coffeateam/coffea-columnservice
    tag: 0.1.0
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 1
      memory: 2G
  scratchDir:
    mountPath: /opt/app
    default_spec:
      emptyDir: {}
    # spec:
    #   persistentVolumeClaim:
    #     claimName: notebook-pvc
  tolerations: []
  nodeSelector: {}
  affinity: {}
