apiVersion: v1
kind: Service
metadata:
  name: {{ include "coffea-farm.fullname" . }}-columnservice
  labels:
    {{- include "coffea-farm.labels" . | nindent 4 }}
    component: columnservice
spec:
  type: {{ .Values.columnservice.service.type }}
  ports:
    - port: {{ .Values.columnservice.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "coffea-farm.selectorLabels" . | nindent 4 }}
    component: columnservice
