apiVersion: v1
kind: Service
metadata:
  name: {{ include "coffea-farm.fullname" . }}-scheduler
  labels:
    {{- include "coffea-farm.labels" . | nindent 4 }}
    component: scheduler
spec:
  type: {{ .Values.scheduler.service.type }}
  ports:
    - name: dask
      port: {{ .Values.scheduler.service.port }}
      targetPort: 8786
      protocol: TCP
    - name: daskui
      port: {{ .Values.scheduler.service.uiport }}
      targetPort: 8787
      protocol: TCP
  selector:
    {{- include "coffea-farm.selectorLabels" . | nindent 4 }}
    component: scheduler
  {{- with .Values.scheduler.service.externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
